### ISSUE TITLE
Better handling of delimiting punctuation around words to abbreviate

### ISSUE THREAD

**Issue by logological** [compholio/jabbrv#35]
jabbrv fails to abbreviate words when they are preceded by delimiting punctuation (opening parentheses, quotation marks, etc.), and when it abbreviates words, it incorrectly removes any delimiting punctuation that follows.  Consider the following minimal example:

```
\JournalTitle{Journal of History (European and International)}
```

Here I expect the output

> J. Hist. (Eur. Int.)

but instead I get

> J. Hist. (European Int.

**Comment by compholio** [comment]
@logological I have not previously run into this in a journal title, thank you for bringing it to my attention.  Due to the way that special characters are treated internally in the package it should not be _too_ hard to add some handling for this case.  Can you give me a list of the characters that are specifically giving you difficulty?  I can think of some characters that might need to be handled differently (directional quotations come to mind), so I'd like to prioritize whichever ones you're having trouble with.

**Comment by logological** [comment]
The only ones I am actually having problem with are parentheses, as in the real-life journal title `Journal of Jiangsu University (Natural Science Edition)`.

However, I thought it prudent to report that I could also reproduce the problem with quotation marks. The Scimago database includes a number of journal titles that include single or double quotation marks, and although none of these titles put quotation marks next to an abbreviatable word, I suppose there's always the possibility that some future journal title will.

**Comment by compholio** [comment]
@logological The parenthesis issue should be fixed by the update that I just pushed.  I'm hesitant to proactively fix quotation marks until someone needs support for it, as I can foresee a variety of scenarios where that might not work out very well.  I'm also anticipating that I might get some regressions from this update (parenthesis are similar, since they need to be changed into "active characters" for this solution to work properly), so I don't want to make too many changes at once.  Please let me know if you have any trouble!
